table SubCategoría
	lineageTag: dc6f0908-5cb9-4047-9e98-630f93575239

	column SubCategoryKey
		dataType: int64
		formatString: 0
		lineageTag: dc5e5574-a0b3-4538-b33f-a77f31802a39
		summarizeBy: none
		sourceColumn: SubCategoryKey

		annotation SummarizationSetBy = Automatic

	column NombreSubCategoria
		dataType: string
		lineageTag: ab5a0c95-f7f7-4b2d-b9f4-f7b19fd350f7
		summarizeBy: none
		sourceColumn: NombreSubCategoria

		annotation SummarizationSetBy = Automatic

	partition SubCategoría = m
		mode: import
		source =
				let
				    Source = Sql.Databases("tdw-assesment.cwb0siyssle1.us-east-1.rds.amazonaws.com"),
				    assesment = Source{[Name="assesment"]}[Data],
				    Data_SubCategory = assesment{[Schema="Data",Item="SubCategory"]}[Data],
				    #"Renamed Columns" = Table.RenameColumns(Data_SubCategory,{{"SubCategoryName", "NombreSubCategoria"}})
				in
				    #"Renamed Columns"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

