select [_].[Date] as [Fecha],
    [_].[DateName] as [Dia],
    [_].[QuarterName] as [NombreTrimestre],
    [_].[MonthName] as [Mes],
    [_].[DayOfYear] as [DiaDelAño],
    [_].[DayOfMonth] as [DiaDelMes],
    [_].[DayOfWeek] as [DiaDeLaSemana],
    [_].[WeekOfYear] as [SemanaDelAño],
    [_].[MonthOfYear] as [MesDelAño],
    [_].[MonthOfQuarter] as [MesDelTrimestre],
    [_].[QuarterOfYear] as [TrimestreDelAño],
    [_].[WeekISO] as [SemanaISO],
    [_].[DaysLastMonth] as [DiasUltimoMes],
    [_].[DaysThisMonth] as [DiasEsteMes],
    [_].[DaysNextMonth] as [DiasEnSiguienteMes],
    [_].[DaysNext3Months] as [DiasSiguientes3Meses],
    [_].[LeapYear] as [AñoBisiesto]
from [dbo].[Calendario] as [_]