select [_].[CustomerKey] as [CustomerKey],
    [_].[GeoAreaKey] as [GeoAreaKey],
    [_].[StartDT] as [FechaInicio],
    [_].[EndDT] as [FechaFin],
    [_].[Continent] as [Continente],
    [_].[Gender] as [Genero],
    [_].[Title] as [Titulo],
    [_].[GivenName] as [Nombre],
    [_].[MiddleInitial] as [InicialSegundoNombre],
    [_].[Surname] as [Apellido],
    [_].[StreetAddress] as [Direccion],
    [_].[City] as [Ciudad],
    [_].[ZipCode] as [CodigoPostal],
    [_].[StateKey] as [StateKey],
    [_].[Birthday] as [FechaCumpleaños],
    [_].[Age] as [Edad],
    [_].[Occupation] as [Ocupacion],
    [_].[Company] as [Compañia],
    [_].[Vehicle] as [Vehiculo],
    [_].[Latitude] as [Lalitud],
    [_].[Longitude] as [Longitud]
from [Data].[Customer] as [_]